name: acc_hack
description: "Flutter mobile for Accenture Hackathon 2025"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_hooks: ^0.20.5
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # Data Classes
  freezed_annotation: ^2.4.4

  # JSON
  json_annotation: ^4.8.1

  # Dependency injection
  get_it: ^7.7.0
  injectable: ^2.4.4

  # UI
  gap: ^3.0.1
  cached_network_image: ^3.4.0
  flutter_typeahead: ^5.2.0
  easy_rich_text: ^2.2.0

  # Navigation
  auto_route: ^9.1.0

  # Network
  retrofit: ^4.4.1
  dio: ^5.7.0

  # MAPS
  google_maps_flutter: ^2.6.0

  # ENV
  flutter_dotenv: ^5.1.0

  # Typography
  google_fonts: ^6.2.1

  # Web
  universal_html: ^2.2.4

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  melos: ^6.1.0
  mason: ^0.1.0-dev.57
  mason_cli: ^0.1.0-dev.55
  build_runner: ^2.4.12
  freezed: ^2.5.7
  auto_route_generator: ^9.0.0
  retrofit_generator: ^9.1.2
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - dotenv
    - assets/
    - assets/images/
    - assets/icons/
